### PR TITLE
Use psycopg2 for PostgreSQL DB operations

### PR DESCRIPTION
**Pull request by ryancausey**
*Issue #, if available:*
Partially related to #24.

*Description of changes:*
Updated the PostgreSQL rotation functions to use psycopg2. I've confirmed using this that I can successfully rotate credentials for the single user rotation use case in the AWS Lambda Python 3.7 runtime.

This was mainly motivated by issues I encountered trying to get `pg` and `pgdb` packaged properly for Lambda. Since I am using Terraform to deploy the secret and its rotation function I cannot rely on the serverless application repository version usually deployed via the console. This has the nice side effect of making the deployment package much smaller, since for some reason pip installing `pg` or `pgdb` installs a bunch of OpenGL stuff.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by siassaj** [comment]
@ryancausey

I ran into weirdness too, `pg` & `pgdb` are coming from `pygresql`. It's probably better to move to psycopg2 in any case.

However my blocker is on getting libpq.so.5 into the serverless machine, how are you getting that to work?

**Comment by ryancausey** [comment]
@siassaj I used `pip install psycopg2-binary` to work around this. See: https://www.psycopg.org/docs/install.html#binary-install-from-pypi

I haven't personally run into issues the docs mention with the binary install, but your mileage may vary.

**Comment by joebaro** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by ryancausey** [comment]
@joebaro I've rebased this onto the most recent version of master as of the time of writing this. Let me know if there are any issues to resolve. Thanks.

**Review by Jesse-Hills — APPROVED** [review]

**Comment by jbct** [comment]
Thank you for the pull request. Unfortunately we have no plans at this time to migrate to psycopg2.

**Pull request closed without merging**
