### PR TITLE
Rotate Active Directory user credentials in AWS Directory Services

### PR DESCRIPTION
**Pull request by brianjbeach**
I have added a new Lambda Function that rotates Active Directory user credentials in AWS Directory Services. This is using the DS ResetUserPassword API. The DS API does not support creating new users and therefore this only supports single user rotations. In addition, this function does not rotate AD credentials in a self managed directory. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by followben** [comment]
Thanks for the sample @brianjbeach - we have exactly this use case. Any chance of a review/ merge @madsid et al?

**Comment by madsid** [comment]
Hi @brianjbeach, We appreciate you contributing to our sample code. 

The new Lambda functions may require a thorough review before approval and I will start reviewing soon.

**Comment by followben** [comment]
Any advance on this @madsid?

**Review by N3RG4L — CHANGES_REQUESTED** [review]
Hi !
using botocore exeptions is better for debug. (just by importing botocore + adding **botocore.exceptions.ClientError as error** in the **except** line, and raising the **error** instead of custom valueError.

Regards,

**Comment by josjaf** [comment]
Is there any reason this hasn't been merged? I'd love to use this Lambda?

**Comment by smhmhmd** [comment]
https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/tree/master/SecretsManagerActiveDirectoryRotationSingleUser

**Comment by joebaro** [comment]
Merged in [PR 67](https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/pull/67).

**Pull request closed without merging**
