### PR TITLE
Adding .Net based framework for secret rotation and example lambda function for Let's Encrypt account keys stored in Secret Manager

### PR DESCRIPTION
**Pull request by paulfryer**
*Issue #, if available:*

*Description of changes:*
Added source code for a .Net based lambda function to rotate secrets. Also included an example for Let's Encrypt private keys.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by paulfryer** [comment]
Checking on status here. It's been a couple months now can we get this checked in please.

**Comment by rstevens011** [comment]
Hello @paulfryer ,
Sorry for the delay in response, reviewing this is in our backlog and we hope to get back to you soon.

**Comment by chace86** [comment]
@paulfryer thank you for putting this together. This was immensely helpful!

**Comment by Welchen** [comment]
Is this every going to be added in or something added for .NET?

**Comment by jbct** [comment]
Hi paulfryer - thank you for the pull request. Unfortunately we don't currently have any plans to support 3rd-party integrations like Let's Encrypt at this time. All samples are being provided in Python for its ease of use templates. Customers can modify as they see fit for their environment.

**Pull request closed without merging**
